### PR TITLE
Support for ZF3 and slm/queue v1.0

### PR DESCRIPTION
**Pull request by boesing**
Added support for ZF3 but had to drop PHP 5.3 and PHP 5.4 support.
In addition I've added PHP 7 and PHP 7.1.

### CODE REVIEW

**Comment by boesing** [comment]
@juriansluiman Would you please consider merging this? Could need that in a project.

**Comment by joepsyko** [comment]
Hello,

I tested your branch in my zf3 project.

I think you should change one more thing.

When I run the code I get the following error:

> Usage of Zend\ServiceManager\ServiceManager::getServiceLocator is deprecated since v3.0.0; please use the container passed to the factory instead

This is because you put this code inside the factory method called by zf3:

```
if (method_exists($container, 'getServiceLocator')) {
        $container = $container->getServiceLocator() ?: $container;
}
```

I already had a module with support for both zf2 and zf3 and I know that zf2 uses the createService() method while zf3 uses the __invoke method, so you don't need to check if the method exists because is deprecated, simply remove those lines fix the problem.

I hope I explained the problem, thank you
Joe

**Comment by boesing** [comment]
Since deprecated is not a serious error, this is exactly as expected.
I wont create two methods just to avoid a deprecated notice.
You can ignore any deprecation errors by setting the proper `error_reporting` level.

To make this work with ZF2 and ZF3, this call is necessary.

**Comment by joepsyko** [comment]
I don't understand why you say that the call is necessary, since zf2 call the createService() service while zf3 calls the __invoke() method.

Can you explain me please?

Thank you

**Comment by boesing** [comment]
Didn't got you right. Actually I thought you wanted to remove the call at all.
Moved it to the `Zend\ServiceManager\FactoryInterface::createService` method.

**Comment by joepsyko** [comment]
Thank you

**Comment by joepsyko** [comment]
I'm sorry to bother you again, but you should fix the same thing in BeanstalkdWorkerControllerFactory, thank you.

**Comment by boesing** [comment]
I guess that this repository might be dead. 
The last PR was merged in 2015.

@juriansluiman If you want me to take over this repository, please give me a note so I can maintain this as long as I have time.

**Comment by joepsyko** [comment]
I'm also available to maintain the repository

**Pull request closed without merging**
